version: '3.8'

services:
  minha-api:
    container_name: fl-refs-container
    build: .
    env_file:
      - myenv.env
    # variables values obtained from local/private .env file
    environment:
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_JDBC_DRIVER: ${DB_JDBC_DRIVER}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:80"
